
image:
  repository: 714487969091.dkr.ecr.eu-central-1.amazonaws.com/scrapper-admin-frontend
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: NodePort
  port: 30000

ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: scrapper-admin-frontend.local
      paths: ["/"]
