apiVersion: v1
kind: Service
metadata:
  name: {{ include "scrapper-admin-frontend.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      nodePort: 30000
      protocol: TCP
  selector:
    app: {{ include "scrapper-admin-frontend.fullname" . }}
