name: Deploy to Minikube via ngrok

on:
  push:
    branches:
      - main  # Set this to the branch you want to deploy from

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Set this to the node version you are using

      - name: Install dependencies
        run: npm install

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          IMAGE_REPO_NAME=scrapper-admin-frontend  # Set your ECR repository name
          IMAGE_NAME=scrapper-admin-frontend  # Set your image name
          
          # Build the Docker image
          docker build -t $IMAGE_NAME .
          
          # Tag the Docker image with the ECR registry
          docker tag $IMAGE_NAME $ECR_REGISTRY/$IMAGE_REPO_NAME:$IMAGE_TAG
          
          # Push the Docker image to ECR
          docker push $ECR_REGISTRY/$IMAGE_REPO_NAME:$IMAGE_TAG
   
      - name: Install Pulumi CLI
        uses: pulumi/action-install-pulumi-cli@v1

      - name: Decode kubeconfig from base64
        run: echo "${{ secrets.MINIKUBE_KUBECONFIG }}" | base64 -d > decoded-kubeconfig

      - name: Install dependencies
        working-directory: ./pulumi
        run: npm install

      - name: Run Pulumi up
        uses: pulumi/actions@v3
        with:
          command: up
          stack-name: dangg/scrapper-frontend-admin/dev
          work-dir: ./pulumi
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          KUBECONFIG: ${{ github.workspace }}/decoded-kubeconfig
          GITHUB_SHA: ${{ github.sha }}
          # Any other environment variables your Pulumi program might need
